services:
  redis: # Use the correct container name
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persist Redis data (optional, but recommended)

volumes:
  redis_data:  # Define the named volume