"""adding importance_sample_messages table

Revision ID: 2f7ca677dd01
Revises: ebbc963f148e
Create Date: 2025-03-07 12:16:12.036201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f7ca677dd01'
down_revision: Union[str, None] = 'ebbc963f148e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importance_sample_messages',
    sa.Column('sample_message', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.PrimaryKeyConstraint('sample_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importance_sample_messages')
    # ### end Alembic commands ###
