"""Updating counsellor message history

Revision ID: 3799c26a248c
Revises: 6500ce87a349
Create Date: 2025-02-21 10:06:03.034829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3799c26a248c'
down_revision: Union[str, None] = '6500ce87a349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counsellor_messages_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('counsellor_response', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counsellor_messages_history_id'), 'counsellor_messages_history', ['id'], unique=False)
    op.drop_index('ix_counsellor_messages_id', table_name='counsellor_messages')
    op.drop_table('counsellor_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counsellor_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counsellor_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='counsellor_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='counsellor_messages_pkey')
    )
    op.create_index('ix_counsellor_messages_id', 'counsellor_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_counsellor_messages_history_id'), table_name='counsellor_messages_history')
    op.drop_table('counsellor_messages_history')
    # ### end Alembic commands ###
