"""Fix user's relationships

Revision ID: 4af95e0c5fbc
Revises: fa803f0f9793
Create Date: 2025-02-21 11:18:23.386005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af95e0c5fbc'
down_revision: Union[str, None] = 'fa803f0f9793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
