"""Adding counsellor message history, user prompt, etc

Revision ID: 6500ce87a349
Revises: 3c7c5a4e0135
Create Date: 2025-02-21 09:54:55.049259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6500ce87a349'
down_revision: Union[str, None] = '3c7c5a4e0135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counsellor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('counsellor_response', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counsellor_messages_id'), 'counsellor_messages', ['id'], unique=False)
    op.create_table('user_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_prompts_id'), 'user_prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_prompts_id'), table_name='user_prompts')
    op.drop_table('user_prompts')
    op.drop_index(op.f('ix_counsellor_messages_id'), table_name='counsellor_messages')
    op.drop_table('counsellor_messages')
    # ### end Alembic commands ###
