"""Update to counsellor_message_history

Revision ID: 65a187e32e08
Revises: 22a1d5b3b3a9
Create Date: 2025-03-09 21:42:06.642736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65a187e32e08'
down_revision: Union[str, None] = '22a1d5b3b3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counsellor_message_history', sa.Column('creation_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('counsellor_message_history', sa.Column('last_updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('counsellor_message_history_embedding_idx', table_name='counsellor_message_history', postgresql_using='hnsw')
    op.drop_column('counsellor_message_history', 'timestamp')
    op.drop_index('importance_sample_messages_embedding_idx', table_name='importance_sample_messages', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('importance_sample_messages_embedding_idx', 'importance_sample_messages', ['embedding'], unique=False, postgresql_using='hnsw')
    op.add_column('counsellor_message_history', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index('counsellor_message_history_embedding_idx', 'counsellor_message_history', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_column('counsellor_message_history', 'last_updated_timestamp')
    op.drop_column('counsellor_message_history', 'creation_timestamp')
    # ### end Alembic commands ###
