"""Updating counsellor message history and tarot reading history

Revision ID: 771ef9205615
Revises: 3799c26a248c
Create Date: 2025-02-21 10:08:26.072021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '771ef9205615'
down_revision: Union[str, None] = '3799c26a248c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counsellor_message_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('counsellor_response', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counsellor_message_history_id'), 'counsellor_message_history', ['id'], unique=False)
    op.create_table('tarot_reading_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reading_date', sa.DateTime(), nullable=True),
    sa.Column('cards_drawn', sa.String(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarot_reading_history_id'), 'tarot_reading_history', ['id'], unique=False)
    op.drop_index('ix_tarot_readings_id', table_name='tarot_readings')
    op.drop_table('tarot_readings')
    op.drop_index('ix_counsellor_messages_history_id', table_name='counsellor_messages_history')
    op.drop_table('counsellor_messages_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counsellor_messages_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counsellor_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='counsellor_messages_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='counsellor_messages_history_pkey')
    )
    op.create_index('ix_counsellor_messages_history_id', 'counsellor_messages_history', ['id'], unique=False)
    op.create_table('tarot_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reading_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cards_drawn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interpretation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tarot_readings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tarot_readings_pkey')
    )
    op.create_index('ix_tarot_readings_id', 'tarot_readings', ['id'], unique=False)
    op.drop_index(op.f('ix_tarot_reading_history_id'), table_name='tarot_reading_history')
    op.drop_table('tarot_reading_history')
    op.drop_index(op.f('ix_counsellor_message_history_id'), table_name='counsellor_message_history')
    op.drop_table('counsellor_message_history')
    # ### end Alembic commands ###
