"""test migration

Revision ID: 815f7c33bb88
Revises: de55c9a47bed
Create Date: 2025-03-02 10:47:44.058432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815f7c33bb88'
down_revision: Union[str, None] = 'de55c9a47bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarot_reading_history', sa.Column('spread', sa.String(), nullable=True))
    op.add_column('tarot_reading_history', sa.Column('user_context', sa.Text(), nullable=True))
    op.alter_column('tarot_reading_history', 'interpretation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarot_reading_history', 'interpretation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tarot_reading_history', 'user_context')
    op.drop_column('tarot_reading_history', 'spread')
    # ### end Alembic commands ###
