"""correcting user and tarot_reading relationship

Revision ID: 9622675d1b31
Revises: d6769d14976e
Create Date: 2025-02-11 11:31:02.341924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9622675d1b31'
down_revision: Union[str, None] = 'd6769d14976e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
