"""adding importance score and embedding columns to Counsellor Message History table

Revision ID: 9938127c5b76
Revises: 815f7c33bb88
Create Date: 2025-03-07 09:47:28.265855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9938127c5b76'
down_revision: Union[str, None] = '815f7c33bb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counsellor_message_history', sa.Column('importance_score', sa.Integer(), nullable=True))
    op.add_column('counsellor_message_history', sa.Column('embedding', postgresql.ARRAY(sa.FLOAT()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counsellor_message_history', 'embedding')
    op.drop_column('counsellor_message_history', 'importance_score')
    # ### end Alembic commands ###
